---

# This is going to be my 2nd playbook 
#

- hosts: web
  tasks:
  - name: Install Tree Package
    apt: name=tree state=present

  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache2 Service 
    service: name=apache2 state=started 
