---
# ansible v2.11
- name: Write ios_facts into a csv file
  hosts: 172.31.0.100
  #connection: network_cli
  gather_facts: yes
  vars:
    output_path: "./"
    filename: "device_report_{{ date }}.csv"

  tasks:
  - name: CSV - Generate output filename
    set_fact: date="{{lookup('pipe','date +%Y%m%d')}}"
    run_once: true

  - name: CSV - Create file and set the header
    lineinfile:
      dest: "{{ output_path }}/{{ filename }}"
      line:
        hostname,image,iostype,model,serialnum,system,version,spacefree_kb,spacetotal_kb
      create: yes
      state: present

  - name: CSV - Get IOS devices facts
    set_fact:
      csv_tmp: >
        {{ ansible_hostname }},{{ ansible_os_family }},{{ ansible_virtualization_type }},{{ ansible_user_id }}


  - debug: msg={{csv_tmp}} 



  - name: Create file 
    file: 
      path: "{{ output_path }}/{{ filename }}" 
      state: touch

  - name: CSV - Write information into .csv file
    lineinfile:
     path: "{{ output_path }}/{{ filename }}"
     line: "{{ csv_tmp }}"
     
